`timescale 1ns/1ps
`default_nettype none
// -----------------------------------------------------------------------------
// AUTO-GENERATED by rtl/tools/gen_rtl_streams.py -- DO NOT EDIT BY HAND.
// Pair-codebook decoder shared by E3 (2slot2lane) and E4 (2slot4lane).
// 5-bit code -> {valid0, slot0, valid1, slot1}; code 31 = EOP -> all invalid.
// Enumeration mirrors experiments/issue2_lane_study.py build_config_codebook().
// -----------------------------------------------------------------------------
module cfg_pair_codebook (
    input  wire [4:0] code,
    output reg        valid0,
    output reg  [2:0] slot0,
    output reg        valid1,
    output reg  [2:0] slot1
);

    always @(*) begin
        case (code)
            5'd0 : begin valid0 = 1'b0; slot0 = 3'd0; valid1 = 1'b0; slot1 = 3'd0; end
            5'd1 : begin valid0 = 1'b0; slot0 = 3'd0; valid1 = 1'b1; slot1 = 3'd0; end
            5'd2 : begin valid0 = 1'b0; slot0 = 3'd0; valid1 = 1'b1; slot1 = 3'd1; end
            5'd3 : begin valid0 = 1'b0; slot0 = 3'd0; valid1 = 1'b1; slot1 = 3'd2; end
            5'd4 : begin valid0 = 1'b0; slot0 = 3'd0; valid1 = 1'b1; slot1 = 3'd3; end
            5'd5 : begin valid0 = 1'b0; slot0 = 3'd0; valid1 = 1'b1; slot1 = 3'd4; end
            5'd6 : begin valid0 = 1'b1; slot0 = 3'd0; valid1 = 1'b0; slot1 = 3'd0; end
            5'd7 : begin valid0 = 1'b1; slot0 = 3'd0; valid1 = 1'b1; slot1 = 3'd1; end
            5'd8 : begin valid0 = 1'b1; slot0 = 3'd0; valid1 = 1'b1; slot1 = 3'd2; end
            5'd9 : begin valid0 = 1'b1; slot0 = 3'd0; valid1 = 1'b1; slot1 = 3'd3; end
            5'd10: begin valid0 = 1'b1; slot0 = 3'd0; valid1 = 1'b1; slot1 = 3'd4; end
            5'd11: begin valid0 = 1'b1; slot0 = 3'd1; valid1 = 1'b0; slot1 = 3'd0; end
            5'd12: begin valid0 = 1'b1; slot0 = 3'd1; valid1 = 1'b1; slot1 = 3'd0; end
            5'd13: begin valid0 = 1'b1; slot0 = 3'd1; valid1 = 1'b1; slot1 = 3'd2; end
            5'd14: begin valid0 = 1'b1; slot0 = 3'd1; valid1 = 1'b1; slot1 = 3'd3; end
            5'd15: begin valid0 = 1'b1; slot0 = 3'd1; valid1 = 1'b1; slot1 = 3'd4; end
            5'd16: begin valid0 = 1'b1; slot0 = 3'd2; valid1 = 1'b0; slot1 = 3'd0; end
            5'd17: begin valid0 = 1'b1; slot0 = 3'd2; valid1 = 1'b1; slot1 = 3'd0; end
            5'd18: begin valid0 = 1'b1; slot0 = 3'd2; valid1 = 1'b1; slot1 = 3'd1; end
            5'd19: begin valid0 = 1'b1; slot0 = 3'd2; valid1 = 1'b1; slot1 = 3'd3; end
            5'd20: begin valid0 = 1'b1; slot0 = 3'd2; valid1 = 1'b1; slot1 = 3'd4; end
            5'd21: begin valid0 = 1'b1; slot0 = 3'd3; valid1 = 1'b0; slot1 = 3'd0; end
            5'd22: begin valid0 = 1'b1; slot0 = 3'd3; valid1 = 1'b1; slot1 = 3'd0; end
            5'd23: begin valid0 = 1'b1; slot0 = 3'd3; valid1 = 1'b1; slot1 = 3'd1; end
            5'd24: begin valid0 = 1'b1; slot0 = 3'd3; valid1 = 1'b1; slot1 = 3'd2; end
            5'd25: begin valid0 = 1'b1; slot0 = 3'd3; valid1 = 1'b1; slot1 = 3'd4; end
            5'd26: begin valid0 = 1'b1; slot0 = 3'd4; valid1 = 1'b0; slot1 = 3'd0; end
            5'd27: begin valid0 = 1'b1; slot0 = 3'd4; valid1 = 1'b1; slot1 = 3'd0; end
            5'd28: begin valid0 = 1'b1; slot0 = 3'd4; valid1 = 1'b1; slot1 = 3'd1; end
            5'd29: begin valid0 = 1'b1; slot0 = 3'd4; valid1 = 1'b1; slot1 = 3'd2; end
            5'd30: begin valid0 = 1'b1; slot0 = 3'd4; valid1 = 1'b1; slot1 = 3'd3; end
            5'd31: begin valid0 = 1'b0; slot0 = 3'd0; valid1 = 1'b0; slot1 = 3'd0; end  // EOP
            default: begin valid0 = 1'b0; slot0 = 3'd0; valid1 = 1'b0; slot1 = 3'd0; end
        endcase
    end

endmodule
`default_nettype wire
